In [8]:
import numpy as np

names = ["Snowballs", "Pizza's", "Silicon Nuggets", "SeaShells"]
A = np.array([
    [1, 1.45, 0.52, 0.72],
    [0.7, 1, 0.31, 0.48],
    [1.95, 3.1, 1, 1.49],
    [1.34, 1.98, 0.64, 1]
])
print(A)
print(names)

[[1.   1.45 0.52 0.72]
 [0.7  1.   0.31 0.48]
 [1.95 3.1  1.   1.49]
 [1.34 1.98 0.64 1.  ]]
['Snowballs', "Pizza's", 'Silicon Nuggets', 'SeaShells']


In [7]:
best_profit = 0
for a in range(4):
    for b in range(4):
        for c in range(4):
            for d in range(4):
                profit = A[3, a] * A[a, b] * A[b, c] * A[c, d] * A[d, 3]
                if profit > best_profit:
                    best_profit = profit
                    best_trades = [3, a, b, c, d, 3]
print(f"Best profit: {best_profit}")
print(f"Best trades: {best_trades}")

Best profit: 1.08868032
Best trades: [3, 0, 2, 1, 0, 3]


In [9]:
for i in range(len(best_trades) - 1):
    print(f"{names[best_trades[i]]} -> {names[best_trades[i + 1]]}")

SeaShells -> Snowballs
Snowballs -> Silicon Nuggets
Silicon Nuggets -> Pizza's
Pizza's -> Snowballs
Snowballs -> SeaShells
